# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-28 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('secret', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('validator', models.TextField(blank=True, null=True)),
                ('validate', models.BooleanField(default=False)),
                ('text_template', models.BooleanField(default=True)),
                ('file_template', models.BooleanField(default=False)),
                ('template', models.TextField(blank=True, null=True)),
                ('template_file', models.URLField(blank=True, null=True)),
                ('outputs', models.CharField(max_length=500)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='core.Application')),
            ],
        ),
    ]
